version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/codegen/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/codegen/swagger"
    schedule:
      interval: "weekly"
