//! Parity tests against Go's moby/buildkit client/llb package.
//!
//! Golden protobuf files were generated by `testdata/go-parity/main.go`
//! using BuildKit v0.31.1. These tests verify structural equivalence:
//! same vertex count, same op-variant sequence.
//!
//! Notable known differences vs Go:
//! - Go omits scratch vertices entirely; Rust emits them as separate source
//!   ops (`scratch://`). This causes scratch-based graphs to have 1 more
//!   vertex in Rust than Go (mkdir, mkfile, file_operations_chain).
//! - Go emits empty `WorkerConstraints` on every vertex; prost omits
//!   zero-length message fields.
//! - Go's `valid_exit_codes` defaults to `[1]` on exec Meta; Rust omits it.
//! - Go omits `image.resolvemode=default` from source attrs; Rust includes it.
//! - Go computes digest from a different canonical encoding,
//!   so digest strings differ even for structurally identical graphs.

use bollard_buildkit_proto::pb;
use bollard_llb::{
    copy, merge, mkdir, mkfile, rm, scratch, shlex, symlink, AddSecret, CacheSharingMode, FileOpts,
    Image, Local, MarshalOpts, MergeOpts, Platform, State,
};
use prost::Message;

fn alpine() -> State {
    State::from(
        Image::new("docker.io/library/alpine:latest").with_platform(Platform::LINUX_AMD64.clone()),
    )
}

fn busybox() -> State {
    State::from(
        Image::new("docker.io/library/busybox:latest").with_platform(Platform::LINUX_AMD64.clone()),
    )
}

fn assert_vertex_count(
    name: &str,
    golden_bytes: &[u8],
    build: impl FnOnce() -> bollard_llb::Definition,
) {
    let rust_def = build();
    let golden_def = pb::Definition::decode(golden_bytes).unwrap();
    assert_eq!(
        rust_def.def.len(),
        golden_def.def.len(),
        "{}: vertex count differs (rust={}, go={})",
        name,
        rust_def.def.len(),
        golden_def.def.len(),
    );

    // Op-variant types match.
    let rust_ops: Vec<pb::Op> = rust_def
        .def
        .iter()
        .map(|b| pb::Op::decode(b.as_slice()).unwrap())
        .collect();
    let golden_ops: Vec<pb::Op> = golden_def
        .def
        .iter()
        .map(|b| pb::Op::decode(b.as_slice()).unwrap())
        .collect();
    let rust_types: Vec<OpKind> = rust_ops.iter().map(op_kind).collect();
    let golden_types: Vec<OpKind> = golden_ops.iter().map(op_kind).collect();
    assert_eq!(
        rust_types, golden_types,
        "{}: op-variant sequence differs",
        name,
    );
}

#[derive(Debug, PartialEq, Eq)]
enum OpKind {
    Source,
    Exec,
    File,
    Build,
    Merge,
    Diff,
    Wrapper,
}

fn op_kind(op: &pb::Op) -> OpKind {
    match &op.op {
        Some(pb::op::Op::Source(_)) => OpKind::Source,
        Some(pb::op::Op::Exec(_)) => OpKind::Exec,
        Some(pb::op::Op::File(_)) => OpKind::File,
        Some(pb::op::Op::Build(_)) => OpKind::Build,
        Some(pb::op::Op::Merge(_)) => OpKind::Merge,
        Some(pb::op::Op::Diff(_)) => OpKind::Diff,
        None => OpKind::Wrapper,
    }
}

// Graphs that should have the same vertex count and op sequence as Go.

#[test]
fn parity_image_run() {
    assert_vertex_count(
        "image_run",
        include_bytes!("../testdata/golden/image_run.llb.pb"),
        || {
            alpine()
                .run(shlex("echo hello"))
                .root()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_merge() {
    assert_vertex_count(
        "merge",
        include_bytes!("../testdata/golden/merge.llb.pb"),
        || {
            merge(vec![alpine(), busybox()], MergeOpts::new())
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_copy_all_flags() {
    assert_vertex_count(
        "copy_all_flags",
        include_bytes!("../testdata/golden/copy_all_flags.llb.pb"),
        || {
            let action = copy(busybox(), "/src", "/dst")
                .with_create_dest_path(true)
                .with_follow_symlinks(true)
                .with_copy_dir_contents_only(true)
                .with_allow_wildcard(true)
                .with_allow_empty_wildcard(true)
                .with_exclude_pattern("*.tmp");
            alpine()
                .file(action, FileOpts::new())
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_secret_as_env() {
    assert_vertex_count(
        "secret_as_env",
        include_bytes!("../testdata/golden/secret_as_env.llb.pb"),
        || {
            alpine()
                .run(shlex("cat /secrets/token"))
                .add_secret(
                    "token",
                    AddSecret {
                        id: String::new(),
                        as_env: true,
                        env_name: Some("TOKEN".into()),
                        target: None,
                        optional: false,
                    },
                )
                .root()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_cache_mount_shared() {
    assert_vertex_count(
        "cache_mount_shared",
        include_bytes!("../testdata/golden/cache_mount_shared.llb.pb"),
        || {
            alpine()
                .run(shlex("echo hello"))
                .add_mount_cache("/cache", "cache-id", CacheSharingMode::Shared)
                .root()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_cache_mount_locked() {
    assert_vertex_count(
        "cache_mount_locked",
        include_bytes!("../testdata/golden/cache_mount_locked.llb.pb"),
        || {
            alpine()
                .run(shlex("echo hello"))
                .add_mount_cache("/cache", "cache-id", CacheSharingMode::Locked)
                .root()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_local_all_attrs() {
    assert_vertex_count(
        "local_all_attrs",
        include_bytes!("../testdata/golden/local_all_attrs.llb.pb"),
        || {
            State::from(
                Local::new("context")
                    .with_follow_paths(["src"])
                    .with_session_id("sess")
                    .with_shared_key_hint("hint")
                    .with_unique_id("unique"),
            )
            .marshal(MarshalOpts::linux_amd64())
            .unwrap()
        },
    );
}

// Scratch-based graphs have 1 more vertex in Rust than Go because Go omits
// scratch sources. We still verify op-type sequence (both end with
// [Source, File, Wrapper] vs Go's [File, Wrapper]).
// For these, just check the Rust output is well-formed.

#[test]
fn parity_mkdir_parents_structural() {
    let def = scratch()
        .file(mkdir("/tmp", 0o755).with_parents(true), FileOpts::new())
        .marshal(MarshalOpts::linux_amd64())
        .unwrap();
    assert_eq!(def.def.len(), 3);
    assert_ends_with_wrapper(&def);
}

#[test]
fn parity_mkfile_structural() {
    let def = scratch()
        .file(mkfile("/hello", 0o644, b"world"), FileOpts::new())
        .marshal(MarshalOpts::linux_amd64())
        .unwrap();
    assert_eq!(def.def.len(), 3);
    assert_ends_with_wrapper(&def);
}

#[test]
fn parity_file_operations_chain_structural() {
    let base = scratch().file(mkdir("/app", 0o755).with_parents(true), FileOpts::new());
    let with_config = base.clone().file(
        mkfile("/app/config.toml", 0o644, b"[server]\nhost = \"0.0.0.0\"\n"),
        FileOpts::new(),
    );
    let with_symlink = with_config.clone().file(
        symlink("/app/config.toml", "/app/current-config"),
        FileOpts::new(),
    );
    let with_copy = with_symlink.clone().file(
        copy(with_symlink, "/app/config.toml", "/app/config.toml.bak").with_create_dest_path(true),
        FileOpts::new(),
    );
    let def = with_copy
        .file(rm("/app/current-config"), FileOpts::new())
        .marshal(MarshalOpts::linux_amd64())
        .unwrap();
    assert_eq!(def.def.len(), 7);
    assert_ends_with_wrapper(&def);
}

fn assert_ends_with_wrapper(def: &bollard_llb::Definition) {
    let last = pb::Op::decode(def.def.last().unwrap().as_slice()).unwrap();
    assert!(
        last.op.is_none(),
        "last vertex should be a wrapper (no op variant)"
    );
}
