//! Parity tests against Go's moby/buildkit client/llb package.
//!
//! Golden protobuf files are generated by the pinned oracle in
//! `../../codegen/llb-parity/`; its version is recorded in the golden manifest.
//! These tests compare complete decoded fields instead of only vertex counts
//! and op-variant sequences.
//!
//! Image references and resolve-mode defaults are normalized by the Rust
//! implementation before operation serialization. Per-operation wire bytes are
//! compared after decoded semantic parity is established.

use bollard_buildkit_proto::{pb, provenance};
use bollard_llb::{
    copy, merge, mkdir, mkfile, rm, scratch, shlex, symlink, AddSecret, CacheSharingMode, FileOpts,
    Image, Local, MarshalOpts, MergeOpts, Platform, ResolveMode, RunOpts, State,
};
use prost::Message;
use sha2::{Digest, Sha256};

mod common;

const MANIFEST_CONTENT: &str = include_str!("../testdata/golden/manifest.json");
const OPS_PROTO_BYTES: &[u8] = include_bytes!("../../codegen/proto/resources/pb/ops.proto");

fn manifest() -> serde_json::Value {
    serde_json::from_str(MANIFEST_CONTENT).expect("golden manifest should be valid JSON")
}

fn go_oracle_version() -> String {
    manifest()
        .get("buildkit_version")
        .and_then(serde_json::Value::as_str)
        .unwrap_or("unknown")
        .to_string()
}

fn generator_version() -> String {
    manifest()
        .get("generator_version")
        .and_then(serde_json::Value::as_str)
        .unwrap_or("unknown")
        .to_string()
}

fn ops_proto_sha256() -> String {
    hex::encode(Sha256::digest(OPS_PROTO_BYTES))
}

fn provenance(name: &str) -> String {
    format!(
        "fixture={} generator={} provenance_buildkit={} provenance_commit={} go_oracle={} ops_proto_sha256={}",
        name,
        generator_version(),
        provenance::BUILDKIT_VERSION,
        provenance::BUILDKIT_COMMIT,
        go_oracle_version(),
        ops_proto_sha256()
    )
}

fn alpine() -> State {
    State::from(Image::new("alpine:latest").unwrap())
}

fn busybox() -> State {
    State::from(Image::new("busybox:latest").unwrap())
}

fn assert_go_parity(
    name: &'static str,
    golden_bytes: &[u8],
    build: impl FnOnce() -> bollard_llb::Definition,
) {
    common::parity::assert_go_parity(name, golden_bytes, build, provenance(name));
}

fn rm_action(definition: &pb::Definition) -> pb::FileActionRm {
    definition
        .def
        .iter()
        .find_map(|bytes| {
            let op = pb::Op::decode(bytes.as_slice()).ok()?;
            let Some(pb::op::Op::File(file)) = op.op else {
                return None;
            };
            file.actions
                .into_iter()
                .find_map(|action| match action.action {
                    Some(pb::file_action::Action::Rm(rm)) => Some(rm),
                    _ => None,
                })
        })
        .expect("definition contains an rm action")
}

fn assert_rm_parity(
    name: &'static str,
    golden_bytes: &[u8],
    build: impl Fn() -> bollard_llb::Definition,
    expected_allow_not_found: bool,
) {
    let rust_rm = rm_action(&build().to_pb());
    let go_definition = pb::Definition::decode(golden_bytes).expect("Go golden should decode");
    let go_rm = rm_action(&go_definition);

    assert_eq!(rust_rm, go_rm, "{name}: rm action");
    assert_eq!(
        rust_rm.allow_not_found, expected_allow_not_found,
        "{name}: allow_not_found"
    );
    common::parity::assert_go_parity(name, golden_bytes, build, provenance(name));
}

fn assert_secret_exec_parity(
    name: &'static str,
    golden_bytes: &[u8],
    build: impl Fn() -> bollard_llb::Definition,
) {
    let rust_def = build().to_pb();
    let go_def = bollard_buildkit_proto::pb::Definition::decode(golden_bytes)
        .expect("Go golden protobuf should decode");

    let find_exec = |def: &bollard_buildkit_proto::pb::Definition| {
        def.def.iter().find_map(|bytes| {
            let op = bollard_buildkit_proto::pb::Op::decode(bytes.as_slice()).ok()?;
            match op.op {
                Some(bollard_buildkit_proto::pb::op::Op::Exec(exec)) => {
                    let digest = common::parity::compute_digest(bytes);
                    Some((exec, digest))
                }
                _ => None,
            }
        })
    };

    let (rust_exec, rust_digest) = find_exec(&rust_def).expect("Rust exec vertex");
    let (go_exec, go_digest) = find_exec(&go_def).expect("Go exec vertex");
    assert_eq!(rust_exec.meta, go_exec.meta, "{name}: exec metadata");
    assert_eq!(rust_exec.mounts, go_exec.mounts, "{name}: exec mounts");
    assert_eq!(rust_exec.network, go_exec.network, "{name}: network");
    assert_eq!(rust_exec.security, go_exec.security, "{name}: security");
    assert_eq!(rust_exec.secretenv, go_exec.secretenv, "{name}: secretenv");
    assert_eq!(
        rust_exec.cdi_devices, go_exec.cdi_devices,
        "{name}: cdi devices"
    );

    let rust_metadata = rust_def
        .metadata
        .get(&rust_digest)
        .expect("Rust exec metadata");
    let go_metadata = go_def.metadata.get(&go_digest).expect("Go exec metadata");
    assert_eq!(rust_metadata.caps, go_metadata.caps, "{name}: capabilities");
    common::parity::assert_go_parity(name, golden_bytes, build, provenance(name));
}

#[test]
fn parity_image_run() {
    assert_go_parity(
        "image_run",
        include_bytes!("../testdata/golden/image_run.llb.pb"),
        || {
            alpine()
                .run(shlex("echo hello").expect("valid parity shell command"))
                .root()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_merge() {
    assert_go_parity(
        "merge",
        include_bytes!("../testdata/golden/merge.llb.pb"),
        || {
            merge(vec![alpine(), busybox()], MergeOpts::new())
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_copy_all_flags() {
    assert_go_parity(
        "copy_all_flags",
        include_bytes!("../testdata/golden/copy_all_flags.llb.pb"),
        || {
            let action = copy(busybox(), "/src", "/dst")
                .with_create_dest_path(true)
                .with_follow_symlinks(true)
                .with_copy_dir_contents_only(true)
                .with_allow_wildcard(true)
                .with_allow_empty_wildcard(true)
                .with_exclude_pattern("*.tmp");
            alpine()
                .file(action, FileOpts::new())
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_secret_as_env() {
    assert_secret_exec_parity(
        "secret_as_env",
        include_bytes!("../testdata/golden/secret_as_env.llb.pb"),
        || {
            alpine()
                .run(shlex("cat /secrets/token").expect("valid parity shell command"))
                .add_secret(
                    "token",
                    AddSecret {
                        id: String::new(),
                        as_env: true,
                        env_name: None,
                        target: None,
                        optional: false,
                        ..Default::default()
                    },
                )
                .root()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_cache_mount_shared() {
    assert_go_parity(
        "cache_mount_shared",
        include_bytes!("../testdata/golden/cache_mount_shared.llb.pb"),
        || {
            alpine()
                .run(shlex("echo hello").expect("valid parity shell command"))
                .add_mount_cache("/cache", "cache-id", CacheSharingMode::Shared)
                .root()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_cache_mount_locked() {
    assert_go_parity(
        "cache_mount_locked",
        include_bytes!("../testdata/golden/cache_mount_locked.llb.pb"),
        || {
            alpine()
                .run(shlex("echo hello").expect("valid parity shell command"))
                .add_mount_cache("/cache", "cache-id", CacheSharingMode::Locked)
                .root()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_multi_mount_ordering() {
    assert_go_parity(
        "multi_mount_ordering",
        include_bytes!("../testdata/golden/multi_mount_ordering.llb.pb"),
        || {
            alpine()
                .run(shlex("echo hello").expect("valid parity shell command"))
                .add_mount_cache("/c", "cache-c", CacheSharingMode::Shared)
                .add_mount_cache("/a", "cache-a", CacheSharingMode::Shared)
                .add_mount_cache("/b", "cache-b", CacheSharingMode::Shared)
                .root()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_local_all_attrs() {
    assert_go_parity(
        "local_all_attrs",
        include_bytes!("../testdata/golden/local_all_attrs.llb.pb"),
        || {
            State::from(
                Local::new("context")
                    .unwrap()
                    .with_follow_paths(["src"])
                    .unwrap()
                    .with_include_patterns(["*.go"])
                    .unwrap()
                    .with_exclude_patterns(["*_test.go"])
                    .unwrap()
                    .with_session_id("sess")
                    .unwrap()
                    .with_shared_key_hint("hint")
                    .unwrap()
                    .with_unique_id("unique")
                    .unwrap(),
            )
            .marshal(MarshalOpts::linux_amd64())
            .unwrap()
        },
    );
}

#[test]
fn parity_mkdir_parents() {
    assert_go_parity(
        "mkdir_parents",
        include_bytes!("../testdata/golden/mkdir_parents.llb.pb"),
        || {
            scratch()
                .unwrap()
                .file(mkdir("/tmp", 0o755).with_parents(true), FileOpts::new())
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_mkfile() {
    assert_go_parity(
        "mkfile",
        include_bytes!("../testdata/golden/mkfile.llb.pb"),
        || {
            scratch()
                .unwrap()
                .file(mkfile("/hello", 0o644, b"world"), FileOpts::new())
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_file_operations_chain() {
    assert_go_parity(
        "file_operations_chain",
        include_bytes!("../testdata/golden/file_operations_chain.llb.pb"),
        || {
            let base = scratch()
                .unwrap()
                .file(mkdir("/app", 0o755).with_parents(true), FileOpts::new())
                .unwrap();
            let with_config = base
                .clone()
                .file(
                    mkfile("/app/config.toml", 0o644, b"[server]\nhost = \"0.0.0.0\"\n"),
                    FileOpts::new(),
                )
                .unwrap();
            let with_symlink = with_config
                .clone()
                .file(
                    symlink("/app/config.toml", "/app/current-config"),
                    FileOpts::new(),
                )
                .unwrap();
            let with_copy = with_symlink
                .clone()
                .file(
                    copy(with_symlink, "/app/config.toml", "/app/config.toml.bak")
                        .with_create_dest_path(true),
                    FileOpts::new(),
                )
                .unwrap();
            with_copy
                .file(rm("/app/current-config"), FileOpts::new())
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_image_resolve_force_pull() {
    assert_go_parity(
        "image_resolve_force_pull",
        include_bytes!("../testdata/golden/image_resolve_force_pull.llb.pb"),
        || {
            State::from(
                Image::new("alpine:latest")
                    .unwrap()
                    .with_resolve_mode(ResolveMode::ForcePull)
                    .unwrap(),
            )
            .run(shlex("echo hello").expect("valid parity shell command"))
            .root()
            .unwrap()
            .marshal(MarshalOpts::linux_amd64())
            .unwrap()
        },
    );
}

#[test]
fn parity_image_resolve_prefer_local() {
    assert_go_parity(
        "image_resolve_prefer_local",
        include_bytes!("../testdata/golden/image_resolve_prefer_local.llb.pb"),
        || {
            State::from(
                Image::new("alpine:latest")
                    .unwrap()
                    .with_resolve_mode(ResolveMode::PreferLocal)
                    .unwrap(),
            )
            .run(shlex("echo hello").expect("valid parity shell command"))
            .root()
            .unwrap()
            .marshal(MarshalOpts::linux_amd64())
            .unwrap()
        },
    );
}

#[test]
fn parity_platform_arm64() {
    assert_go_parity(
        "platform_arm64",
        include_bytes!("../testdata/golden/platform_arm64.llb.pb"),
        || {
            alpine()
                .run(shlex("echo hello").expect("valid parity shell command"))
                .root()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64().with_platform(Platform::LINUX_ARM64))
                .unwrap()
        },
    );
}

#[test]
fn parity_platform_arm_v7() {
    assert_go_parity(
        "platform_arm_v7",
        include_bytes!("../testdata/golden/platform_arm_v7.llb.pb"),
        || {
            alpine()
                .run(shlex("echo hello").expect("valid parity shell command"))
                .root()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64().with_platform(Platform::LINUX_ARM_V7))
                .unwrap()
        },
    );
}

#[test]
fn parity_platform_image_override() {
    assert_go_parity(
        "platform_image_override",
        include_bytes!("../testdata/golden/platform_image_override.llb.pb"),
        || {
            State::from(
                Image::new("alpine:latest")
                    .unwrap()
                    .with_platform(Platform::LINUX_ARM64)
                    .unwrap(),
            )
            .run(shlex("echo image override").expect("valid parity shell command"))
            .root()
            .unwrap()
            .marshal(MarshalOpts::linux_amd64())
            .unwrap()
        },
    );
}

#[test]
fn parity_platform_state_override() {
    assert_go_parity(
        "platform_state_override",
        include_bytes!("../testdata/golden/platform_state_override.llb.pb"),
        || {
            alpine()
                .with_platform(Platform::LINUX_ARM64)
                .run(shlex("echo state override").expect("valid parity shell command"))
                .root()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_platform_mixed() {
    assert_go_parity(
        "platform_mixed",
        include_bytes!("../testdata/golden/platform_mixed.llb.pb"),
        || {
            let arm_v6 = Platform::new("linux", "arm").with_variant("v6");
            let subgraph = State::from(
                Image::new("image2:latest")
                    .unwrap()
                    .with_platform(arm_v6)
                    .unwrap(),
            )
            .run(shlex("cmd-sub").expect("valid parity shell command"))
            .root()
            .unwrap();
            State::from(Image::new("image1:latest").unwrap())
                .run(shlex("cmd-main").expect("valid parity shell command"))
                .add_mount("/mnt", subgraph)
                .root()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_platform_shared_subgraph() {
    assert_go_parity(
        "platform_shared_subgraph",
        include_bytes!("../testdata/golden/platform_shared_subgraph.llb.pb"),
        || {
            let shared = State::from(
                Image::new("shared:latest")
                    .unwrap()
                    .with_platform(Platform::LINUX_ARM64)
                    .unwrap(),
            )
            .run(shlex("cmd-shared").expect("valid parity shell command"))
            .root()
            .unwrap();
            State::from(Image::new("main:latest").unwrap())
                .run(shlex("cmd-main").expect("valid parity shell command"))
                .add_mount("/left", shared.clone())
                .add_mount("/right", shared)
                .root()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_exec_default_meta() {
    assert_go_parity(
        "exec_default_meta",
        include_bytes!("../testdata/golden/exec_default_meta.llb.pb"),
        || {
            alpine()
                .run(RunOpts::default().with_arg("true"))
                .root()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_exec_custom_name_ignore_cache() {
    assert_go_parity(
        "exec_custom_name_ignore_cache",
        include_bytes!("../testdata/golden/exec_custom_name_ignore_cache.llb.pb"),
        || {
            alpine()
                .run(RunOpts {
                    args: vec!["echo".into(), "hello".into()],
                    custom_name: Some("named exec".into()),
                    ignore_cache: true,
                    ..Default::default()
                })
                .root()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_merge_custom_name() {
    assert_go_parity(
        "merge_custom_name",
        include_bytes!("../testdata/golden/merge_custom_name.llb.pb"),
        || {
            merge(
                vec![alpine(), busybox()],
                MergeOpts::new().with_custom_name("merged"),
            )
            .unwrap()
            .marshal(MarshalOpts::linux_amd64())
            .unwrap()
        },
    );
}

#[test]
fn parity_rm_wildcard() {
    assert_go_parity(
        "rm_wildcard",
        include_bytes!("../testdata/golden/rm_wildcard.llb.pb"),
        || {
            scratch()
                .unwrap()
                .file(rm("/tmp/*").with_allow_wildcard(true), FileOpts::new())
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

fn parity_file_ops_rm_definition(allow_not_found: bool) -> bollard_llb::Definition {
    let base = scratch().unwrap();
    let base = base
        .file(mkdir("/app", 0o755).with_parents(true), FileOpts::new())
        .unwrap();
    let base = base
        .file(
            mkfile("/app/config.toml", 0o644, b"[server]\nhost = \"0.0.0.0\"\n"),
            FileOpts::new(),
        )
        .unwrap();
    let base = base
        .file(
            symlink("/app/config.toml", "/app/current-config"),
            FileOpts::new(),
        )
        .unwrap();
    base.file(
        rm("/app/current-config").with_allow_not_found(allow_not_found),
        FileOpts::new(),
    )
    .unwrap()
    .marshal(MarshalOpts::linux_amd64())
    .unwrap()
}

#[test]
fn parity_file_ops_rm() {
    assert_rm_parity(
        "file_ops_rm",
        include_bytes!("../testdata/golden/file_ops_rm.llb.pb"),
        || parity_file_ops_rm_definition(false),
        false,
    );
}

#[test]
fn parity_file_ops_rm_allow_not_found() {
    assert_rm_parity(
        "file_ops_rm_allow_not_found",
        include_bytes!("../testdata/golden/file_ops_rm_allow_not_found.llb.pb"),
        || parity_file_ops_rm_definition(true),
        true,
    );
}

#[test]
fn parity_symlink() {
    assert_go_parity(
        "symlink",
        include_bytes!("../testdata/golden/symlink.llb.pb"),
        || {
            scratch()
                .unwrap()
                .file(symlink("/target", "/link"), FileOpts::new())
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_secret_file_default() {
    assert_secret_exec_parity(
        "secret_file_default",
        include_bytes!("../testdata/golden/secret_file_default.llb.pb"),
        || {
            alpine()
                .run(
                    RunOpts::default()
                        .with_arg("cat")
                        .with_arg("/run/secrets/token"),
                )
                .add_secret(
                    "token",
                    AddSecret {
                        id: String::new(),
                        as_env: false,
                        env_name: None,
                        target: Some("token".into()),
                        optional: false,
                        ..Default::default()
                    },
                )
                .root()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_secret_file_optional() {
    assert_secret_exec_parity(
        "secret_file_optional",
        include_bytes!("../testdata/golden/secret_file_optional.llb.pb"),
        || {
            alpine()
                .run(
                    RunOpts::default()
                        .with_arg("cat")
                        .with_arg("/run/secrets/token"),
                )
                .add_secret(
                    "token",
                    AddSecret {
                        id: String::new(),
                        as_env: false,
                        env_name: None,
                        target: Some("token".into()),
                        optional: true,
                        ..Default::default()
                    },
                )
                .root()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_secret_file_permissions() {
    assert_secret_exec_parity(
        "secret_file_permissions",
        include_bytes!("../testdata/golden/secret_file_permissions.llb.pb"),
        || {
            alpine()
                .run(
                    RunOpts::default()
                        .with_arg("cat")
                        .with_arg("/run/secrets/license"),
                )
                .add_secret(
                    "license",
                    AddSecret {
                        id: "license".into(),
                        as_env: false,
                        env_name: None,
                        target: Some("/run/secrets/license".into()),
                        optional: false,
                        uid: 1000,
                        gid: 1001,
                        mode: 0o440,
                    },
                )
                .root()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_secret_env_explicit_name() {
    assert_secret_exec_parity(
        "secret_env_explicit_name",
        include_bytes!("../testdata/golden/secret_env_explicit_name.llb.pb"),
        || {
            alpine()
                .run(
                    RunOpts::default()
                        .with_arg("cat")
                        .with_arg("/secrets/token"),
                )
                .add_secret(
                    "mysecret",
                    AddSecret {
                        id: String::new(),
                        as_env: true,
                        env_name: Some("MY_SECRET".into()),
                        target: None,
                        optional: false,
                        ..Default::default()
                    },
                )
                .root()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_cache_mount_private() {
    assert_go_parity(
        "cache_mount_private",
        include_bytes!("../testdata/golden/cache_mount_private.llb.pb"),
        || {
            alpine()
                .run(shlex("echo hello").expect("valid parity shell command"))
                .add_mount_cache("/cache", "cache-id", CacheSharingMode::Private)
                .root()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_scratch_direct() {
    assert_go_parity(
        "scratch_direct",
        include_bytes!("../testdata/golden/scratch_direct.llb.pb"),
        || {
            scratch()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_scratch_exec_root() {
    assert_go_parity(
        "scratch_exec_root",
        include_bytes!("../testdata/golden/scratch_exec_root.llb.pb"),
        || {
            scratch()
                .unwrap()
                .run(RunOpts::default().with_arg("echo").with_arg("hello"))
                .root()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_scratch_bind_mount() {
    assert_go_parity(
        "scratch_bind_mount",
        include_bytes!("../testdata/golden/scratch_bind_mount.llb.pb"),
        || {
            alpine()
                .run(shlex("echo hello").expect("valid parity shell command"))
                .add_mount("/scratch", scratch().unwrap())
                .root()
                .unwrap()
                .marshal(MarshalOpts::linux_amd64())
                .unwrap()
        },
    );
}

#[test]
fn parity_provenance_self_check() {
    let go_version = go_oracle_version();
    assert!(
        go_version.starts_with('v'),
        "unexpected Go oracle version: {}",
        go_version
    );
    let hash = ops_proto_sha256();
    assert_eq!(
        hash.len(),
        64,
        "ops.proto hash should be 64 hex chars: {}",
        hash
    );
    assert_ne!(generator_version(), "unknown");
    assert_eq!(
        manifest()
            .get("fixtures")
            .and_then(serde_json::Value::as_array)
            .map(Vec::len),
        Some(43),
        "golden manifest should describe all generated fixtures"
    );
}

#[test]
fn parity_wrapper_matches_go_shape() {
    let rust = alpine()
        .run(shlex("echo hello").expect("valid parity shell command"))
        .root()
        .unwrap()
        .marshal(MarshalOpts::linux_amd64())
        .unwrap()
        .to_pb();
    let go = bollard_buildkit_proto::pb::Definition::decode(
        include_bytes!("../testdata/golden/image_run.llb.pb").as_slice(),
    )
    .unwrap();

    let rust_wrapper =
        bollard_buildkit_proto::pb::Op::decode(rust.def.last().unwrap().as_slice()).unwrap();
    let go_wrapper =
        bollard_buildkit_proto::pb::Op::decode(go.def.last().unwrap().as_slice()).unwrap();

    assert_eq!(rust_wrapper.op, None);
    assert_eq!(go_wrapper.op, None);
    assert_eq!(rust_wrapper.platform, go_wrapper.platform);
    assert_eq!(rust_wrapper.constraints, go_wrapper.constraints);
    assert_eq!(rust_wrapper.inputs.len(), 1);
    assert_eq!(go_wrapper.inputs.len(), 1);

    let rust_wrapper_digest = common::parity::compute_digest(rust.def.last().unwrap());
    let go_wrapper_digest = common::parity::compute_digest(go.def.last().unwrap());
    assert_eq!(rust.def.last(), go.def.last());
    let rust_metadata = rust.metadata.get(&rust_wrapper_digest).unwrap();
    let go_metadata = go.metadata.get(&go_wrapper_digest).unwrap();
    assert_eq!(rust_metadata.caps, go_metadata.caps);
    assert_eq!(rust_metadata.ignore_cache, go_metadata.ignore_cache);
    assert_eq!(rust_metadata.export_cache, go_metadata.export_cache);
}
